[2024-07-25T22:19:35.304+0100] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-25T22:19:35.366+0100] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: jobs_etl.jungle_scraper scheduled__2024-07-24T18:00:00+00:00 [queued]>
[2024-07-25T22:19:35.375+0100] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: jobs_etl.jungle_scraper scheduled__2024-07-24T18:00:00+00:00 [queued]>
[2024-07-25T22:19:35.375+0100] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-25T22:19:35.390+0100] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): jungle_scraper> on 2024-07-24 18:00:00+00:00
[2024-07-25T22:19:35.403+0100] {standard_task_runner.py:63} INFO - Started process 673019 to run task
[2024-07-25T22:19:35.410+0100] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'jobs_etl', 'jungle_scraper', 'scheduled__2024-07-24T18:00:00+00:00', '--job-id', '209', '--raw', '--subdir', 'DAGS_FOLDER/jobs_etl.py', '--cfg-path', '/tmp/tmp0uawjbz4']
[2024-07-25T22:19:35.414+0100] {standard_task_runner.py:91} INFO - Job 209: Subtask jungle_scraper
[2024-07-25T22:19:35.518+0100] {task_command.py:426} INFO - Running <TaskInstance: jobs_etl.jungle_scraper scheduled__2024-07-24T18:00:00+00:00 [running]> on host huser
[2024-07-25T22:19:35.692+0100] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='hassounibarka@gmail.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='jobs_etl' AIRFLOW_CTX_TASK_ID='jungle_scraper' AIRFLOW_CTX_EXECUTION_DATE='2024-07-24T18:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-24T18:00:00+00:00'
[2024-07-25T22:19:35.694+0100] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-25T22:19:51.915+0100] {logging_mixin.py:188} INFO - 9 Jobs for data Scientist
[2024-07-25T22:19:51.917+0100] {logging_mixin.py:188} INFO - data Scientist Job extraction ...
[2024-07-25T22:22:29.633+0100] {logging_mixin.py:188} INFO - 0 Jobs read1 Jobs read2 Jobs read3 Jobs read4 Jobs read5 Jobs read6 Jobs read7 Jobs read8 Jobs read60 Jobs for data analyst
[2024-07-25T22:22:29.635+0100] {logging_mixin.py:188} INFO - data analyst Job extraction ...
[2024-07-25T22:31:47.667+0100] {job.py:218} ERROR - Job heartbeat got an exception
Traceback (most recent call last):
  File "/home/huser/airflow_workspace/airflow_env/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
  File "/home/huser/airflow_workspace/airflow_env/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/huser/airflow_workspace/airflow_env/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/huser/airflow_workspace/airflow_env/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/huser/airflow_workspace/airflow_env/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
  File "/home/huser/airflow_workspace/airflow_env/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/huser/airflow_workspace/airflow_env/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/huser/airflow_workspace/airflow_env/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
  File "/home/huser/airflow_workspace/airflow_env/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/huser/airflow_workspace/airflow_env/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/huser/airflow_workspace/airflow_env/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/huser/airflow_workspace/airflow_env/lib/python3.10/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/huser/airflow_workspace/airflow_env/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/huser/airflow_workspace/airflow_env/lib/python3.10/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: SSL SYSCALL error: EOF detected


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/huser/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/jobs/job.py", line 213, in heartbeat
    heartbeat_callback(session)
  File "/home/huser/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
  File "/home/huser/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/jobs/local_task_job_runner.py", line 258, in heartbeat_callback
    self.task_instance.refresh_from_db()
  File "/home/huser/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/huser/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1821, in refresh_from_db
    _refresh_from_db(task_instance=self, session=session, lock_for_update=lock_for_update)
  File "/home/huser/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 510, in _refresh_from_db
    ti = TaskInstance.get_task_instance(
  File "/home/huser/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/api_internal/internal_api_call.py", line 115, in wrapper
    return func(*args, **kwargs)
  File "/home/huser/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
  File "/home/huser/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1807, in get_task_instance
    return query.one_or_none()
  File "/home/huser/airflow_workspace/airflow_env/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 2850, in one_or_none
    return self._iter().one_or_none()
  File "/home/huser/airflow_workspace/airflow_env/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 2916, in _iter
    result = self.session.execute(
  File "/home/huser/airflow_workspace/airflow_env/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
    conn = self._connection_for_bind(bind)
  File "/home/huser/airflow_workspace/airflow_env/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
    return self._transaction._connection_for_bind(
  File "/home/huser/airflow_workspace/airflow_env/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
    conn = bind.connect()
  File "/home/huser/airflow_workspace/airflow_env/lib/python3.10/site-packages/sqlalchemy/future/engine.py", line 412, in connect
    return super(Engine, self).connect()
  File "/home/huser/airflow_workspace/airflow_env/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3325, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/home/huser/airflow_workspace/airflow_env/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
  File "/home/huser/airflow_workspace/airflow_env/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/home/huser/airflow_workspace/airflow_env/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3374, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/huser/airflow_workspace/airflow_env/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2208, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/huser/airflow_workspace/airflow_env/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/huser/airflow_workspace/airflow_env/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
  File "/home/huser/airflow_workspace/airflow_env/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/huser/airflow_workspace/airflow_env/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/huser/airflow_workspace/airflow_env/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/huser/airflow_workspace/airflow_env/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
  File "/home/huser/airflow_workspace/airflow_env/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/huser/airflow_workspace/airflow_env/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/huser/airflow_workspace/airflow_env/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
  File "/home/huser/airflow_workspace/airflow_env/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/huser/airflow_workspace/airflow_env/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/huser/airflow_workspace/airflow_env/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/huser/airflow_workspace/airflow_env/lib/python3.10/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/huser/airflow_workspace/airflow_env/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/huser/airflow_workspace/airflow_env/lib/python3.10/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) connection to server at "localhost" (127.0.0.1), port 5432 failed: SSL SYSCALL error: EOF detected

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2024-07-25T22:31:47.817+0100] {job.py:226} ERROR - Job heartbeat failed with error. Scheduler is in unhealthy state
[2024-07-25T22:38:38.209+0100] {logging_mixin.py:188} WARNING - Exception in thread Thread-6 (_handle_event_loop):
[2024-07-25T22:38:39.119+0100] {logging_mixin.py:188} WARNING - Traceback (most recent call last):
[2024-07-25T22:38:39.702+0100] {logging_mixin.py:188} WARNING -   File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
[2024-07-25T22:38:41.224+0100] {logging_mixin.py:188} WARNING -     self.run()
[2024-07-25T22:38:41.910+0100] {logging_mixin.py:188} WARNING -   File "/usr/lib/python3.10/threading.py", line 953, in run
[2024-07-25T22:38:42.971+0100] {logging_mixin.py:188} WARNING -     self._target(*self._args, **self._kwargs)
[2024-07-25T22:38:44.977+0100] {logging_mixin.py:188} WARNING -   File "/home/huser/airflow_workspace/airflow_env/lib/python3.10/site-packages/DrissionPage/_base/driver.py", line 156, in _handle_event_loop
[2024-07-25T22:38:46.918+0100] {logging_mixin.py:188} WARNING -     function(**event['params'])
[2024-07-25T22:38:49.761+0100] {logging_mixin.py:188} WARNING -   File "/home/huser/airflow_workspace/airflow_env/lib/python3.10/site-packages/DrissionPage/_pages/chromium_base.py", line 221, in _onDomContentEventFired
[2024-07-25T22:38:51.142+0100] {logging_mixin.py:188} WARNING -     if self._get_document(self._load_end_time - perf_counter() - .1):
[2024-07-25T22:38:52.042+0100] {logging_mixin.py:188} WARNING -   File "/home/huser/airflow_workspace/airflow_env/lib/python3.10/site-packages/DrissionPage/_pages/chromium_base.py", line 183, in _get_document
[2024-07-25T22:38:53.061+0100] {logging_mixin.py:188} WARNING -     r = self.run_cdp('Page.getFrameTree')
[2024-07-25T22:38:54.413+0100] {logging_mixin.py:188} WARNING -   File "/home/huser/airflow_workspace/airflow_env/lib/python3.10/site-packages/DrissionPage/_pages/chromium_base.py", line 424, in run_cdp
[2024-07-25T22:38:55.512+0100] {logging_mixin.py:188} WARNING -     return r if __ERROR__ not in r else raise_error(r, ignore)
[2024-07-25T22:38:56.439+0100] {logging_mixin.py:188} WARNING -   File "/home/huser/airflow_workspace/airflow_env/lib/python3.10/site-packages/DrissionPage/_functions/tools.py", line 241, in raise_error
[2024-07-25T22:38:57.555+0100] {logging_mixin.py:188} WARNING -     raise r
[2024-07-25T22:38:57.789+0100] {logging_mixin.py:188} WARNING - TimeoutError: 
错误：timeout
方法：Page.getFrameTree
参数：{'_timeout': 30}
版本：4.0.5.6
出现这个错误可能意味着程序有bug，请把错误信息和重现方法告知作者，谢谢。
报告网站：https://gitee.com/g1879/DrissionPage/issues
