[2024-08-05T20:10:42.278+0100] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-05T20:10:42.329+0100] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: jobs_etl.linkedIn_scraper scheduled__2024-08-04T18:00:00+00:00 [queued]>
[2024-08-05T20:10:42.337+0100] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: jobs_etl.linkedIn_scraper scheduled__2024-08-04T18:00:00+00:00 [queued]>
[2024-08-05T20:10:42.338+0100] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-08-05T20:10:42.354+0100] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): linkedIn_scraper> on 2024-08-04 18:00:00+00:00
[2024-08-05T20:10:42.365+0100] {standard_task_runner.py:63} INFO - Started process 588036 to run task
[2024-08-05T20:10:42.370+0100] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'jobs_etl', 'linkedIn_scraper', 'scheduled__2024-08-04T18:00:00+00:00', '--job-id', '297', '--raw', '--subdir', 'DAGS_FOLDER/jobs_etl.py', '--cfg-path', '/tmp/tmp4jxb2e5m']
[2024-08-05T20:10:42.373+0100] {standard_task_runner.py:91} INFO - Job 297: Subtask linkedIn_scraper
[2024-08-05T20:10:42.469+0100] {task_command.py:426} INFO - Running <TaskInstance: jobs_etl.linkedIn_scraper scheduled__2024-08-04T18:00:00+00:00 [running]> on host huser
[2024-08-05T20:10:42.618+0100] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='hassounibarka@gmail.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='jobs_etl' AIRFLOW_CTX_TASK_ID='linkedIn_scraper' AIRFLOW_CTX_EXECUTION_DATE='2024-08-04T18:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-08-04T18:00:00+00:00'
[2024-08-05T20:10:42.619+0100] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-05T20:12:30.306+0100] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-05T20:12:30.308+0100] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/huser/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/huser/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/huser/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/huser/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/huser/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/huser/airflow_workspace/airflow/dags/jobs_etl.py", line 41, in get_linked_data
    driver = linked_scraper.connect()
  File "/home/huser/airflow_workspace/airflow/dags/Jobs/LinkedScrper.py", line 22, in connect
    username = driver.find_element(By.ID, "username")
  File "/home/huser/airflow_workspace/airflow_env/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 748, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
  File "/home/huser/airflow_workspace/airflow_env/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 354, in execute
    self.error_handler.check_response(response)
  File "/home/huser/airflow_workspace/airflow_env/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="username"]"}
  (Session info: chrome=126.0.6478.114); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
#0 0x56d08d69e69a <unknown>
#1 0x56d08d3810dc <unknown>
#2 0x56d08d3cd931 <unknown>
#3 0x56d08d3cda21 <unknown>
#4 0x56d08d412234 <unknown>
#5 0x56d08d3f089d <unknown>
#6 0x56d08d40f5c3 <unknown>
#7 0x56d08d3f0613 <unknown>
#8 0x56d08d3c04f7 <unknown>
#9 0x56d08d3c0e4e <unknown>
#10 0x56d08d66486b <unknown>
#11 0x56d08d668911 <unknown>
#12 0x56d08d65035e <unknown>
#13 0x56d08d669472 <unknown>
#14 0x56d08d634cbf <unknown>
#15 0x56d08d68e098 <unknown>
#16 0x56d08d68e270 <unknown>
#17 0x56d08d69d7cc <unknown>
#18 0x77b57cc94ac3 <unknown>

[2024-08-05T20:12:30.342+0100] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=jobs_etl, task_id=linkedIn_scraper, run_id=scheduled__2024-08-04T18:00:00+00:00, execution_date=20240804T180000, start_date=20240805T191042, end_date=20240805T191230
[2024-08-05T20:12:30.357+0100] {standard_task_runner.py:110} ERROR - Failed to execute job 297 for task linkedIn_scraper (Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="username"]"}
  (Session info: chrome=126.0.6478.114); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
#0 0x56d08d69e69a <unknown>
#1 0x56d08d3810dc <unknown>
#2 0x56d08d3cd931 <unknown>
#3 0x56d08d3cda21 <unknown>
#4 0x56d08d412234 <unknown>
#5 0x56d08d3f089d <unknown>
#6 0x56d08d40f5c3 <unknown>
#7 0x56d08d3f0613 <unknown>
#8 0x56d08d3c04f7 <unknown>
#9 0x56d08d3c0e4e <unknown>
#10 0x56d08d66486b <unknown>
#11 0x56d08d668911 <unknown>
#12 0x56d08d65035e <unknown>
#13 0x56d08d669472 <unknown>
#14 0x56d08d634cbf <unknown>
#15 0x56d08d68e098 <unknown>
#16 0x56d08d68e270 <unknown>
#17 0x56d08d69d7cc <unknown>
#18 0x77b57cc94ac3 <unknown>
; 588036)
[2024-08-05T20:12:30.383+0100] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-08-05T20:12:30.421+0100] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-05T20:12:30.423+0100] {local_task_job_runner.py:222} INFO - ::endgroup::
