[2024-07-27T14:41:08.422+0100] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-27T14:41:08.467+0100] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: jobs_etl.indeed_scraper scheduled__2024-07-25T18:00:00+00:00 [queued]>
[2024-07-27T14:41:08.477+0100] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: jobs_etl.indeed_scraper scheduled__2024-07-25T18:00:00+00:00 [queued]>
[2024-07-27T14:41:08.478+0100] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-07-27T14:41:08.491+0100] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): indeed_scraper> on 2024-07-25 18:00:00+00:00
[2024-07-27T14:41:08.501+0100] {standard_task_runner.py:63} INFO - Started process 3702 to run task
[2024-07-27T14:41:08.506+0100] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'jobs_etl', 'indeed_scraper', 'scheduled__2024-07-25T18:00:00+00:00', '--job-id', '221', '--raw', '--subdir', 'DAGS_FOLDER/jobs_etl.py', '--cfg-path', '/tmp/tmpx584_bb9']
[2024-07-27T14:41:08.509+0100] {standard_task_runner.py:91} INFO - Job 221: Subtask indeed_scraper
[2024-07-27T14:41:08.607+0100] {task_command.py:426} INFO - Running <TaskInstance: jobs_etl.indeed_scraper scheduled__2024-07-25T18:00:00+00:00 [running]> on host huser
[2024-07-27T14:41:08.759+0100] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='hassounibarka@gmail.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='jobs_etl' AIRFLOW_CTX_TASK_ID='indeed_scraper' AIRFLOW_CTX_EXECUTION_DATE='2024-07-25T18:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-25T18:00:00+00:00'
[2024-07-27T14:41:08.761+0100] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-27T14:42:37.597+0100] {logging_mixin.py:188} INFO - 30 Jobs found for data Scientist
[2024-07-27T14:42:45.136+0100] {local_task_job_runner.py:310} WARNING - State of this instance has been externally set to success. Terminating instance.
[2024-07-27T14:42:45.137+0100] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-07-27T14:42:45.150+0100] {process_utils.py:132} INFO - Sending 15 to group 3702. PIDs of all processes in the group: [4950, 3702]
[2024-07-27T14:42:45.150+0100] {process_utils.py:87} INFO - Sending the signal 15 to group 3702
[2024-07-27T14:42:45.151+0100] {taskinstance.py:2611} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-07-27T14:42:45.151+0100] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-27T14:42:45.206+0100] {process_utils.py:80} INFO - Process psutil.Process(pid=4950, status='terminated', started='14:42:37') (4950) terminated with exit code None
[2024-07-27T14:42:45.207+0100] {process_utils.py:80} INFO - Process psutil.Process(pid=3702, status='terminated', exitcode=0, started='14:41:07') (3702) terminated with exit code 0
